<?xml version="1.0"?>
<!--
  Copyright 1999-2004 The Apache Software Foundation

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->
<!DOCTYPE status [
<!ELEMENT status (developers, todo, changes)>
<!ELEMENT developers (person+)>
<!ELEMENT person EMPTY>
<!ATTLIST person
	name CDATA #REQUIRED
	email CDATA #REQUIRED
	id CDATA #REQUIRED
>
<!ELEMENT todo (actions+)>
<!ELEMENT actions (action+)>
<!ATTLIST actions
	priority (high | medium | low) #REQUIRED
>
<!ELEMENT action (#PCDATA | link | br | code)*>
<!ATTLIST action
	context (build | code | docs) #IMPLIED
	assigned-to CDATA #IMPLIED
	dev CDATA #IMPLIED
	type (add | fix | remove | update) #IMPLIED
	fixes-bug CDATA #IMPLIED
	due-to CDATA #IMPLIED
	due-to-email CDATA #IMPLIED
>
<!ELEMENT changes (release+)>
<!ELEMENT code (#PCDATA)>
<!ELEMENT br EMPTY>
<!ELEMENT link (#PCDATA)>
<!ATTLIST link
	href CDATA #REQUIRED
>
<!ELEMENT release (action+)>
<!ATTLIST release
	version CDATA #REQUIRED
	date CDATA #REQUIRED
>
<!ENTITY eacute           "&#x000E9;">
<!ENTITY ouml             "&#x000F6;">
<!ENTITY uuml             "&#x000FC;">
]>

<!-- CVS $Id: status.xml,v 1.190 2004/03/23 07:59:29 antonio Exp $:-->

<status>
 <developers>
  <!-- in strict alphabetical order -->
  <person name="Donald Ball" email="balld@apache.org" id="DB"/>
  <person name="Nicola Ken Barozzi" email="nicolaken@apache.org" id="NKB"/>
  <person name="Ross Burton" email="rossb@apache.org" id="RB"/>
  <person name="Mark Butler" email="butlermh@apache.org" id="MB"/>
  <person name="Ugo Cei" email="ugo@apache.org" id="UC"/>
  <person name="Marcus Crafter" email="crafterm@apache.org" id="MC"/>
  <person name="David Crossley" email="crossley@apache.org" id="DC"/>
  <person name="Torsten Curdt" email="tcurdt@apache.org" id="TC"/>
  <person name="Bertrand Delacr&#233;taz" email="bdelacretaz@apache.org" id="BD"/>
  <person name="Bruno Dumon" email="bruno@apache.org" id="BRD"/>
  <person name="Gerhard Froehlich" email="froehlich@apache.org" id="GF"/>
  <person name="Pierpaolo Fumagalli" email="pier@apache.org" id="PF"/>
  <person name="Antonio Gallardo" email="antonio@apache.org" id="AG"/>
  <person name="Vadim Gritsenko" email="vgritsenko@apache.org" id="VG"/>
  <person name="Christian Haul" email="haul@apache.org" id="CH"/>
  <person name="J&#246;rg Heinicke" email="joerg@apache.org" id="JH"/>
  <person name="Unico Hommes" email="unico@apache.org" id="UH"/>
  <person name="Geoff Howard" email="ghoward@apache.org" id="GH"/>
  <person name="Bernhard Huber" email="huber@apache.org" id="BH"/>
  <person name="Ivelin Atanasoff Ivanov" email="ivelin@apache.org" id="IAI"/>
  <person name="Matthew Langham" email="mlangham@apache.org" id="BL"/>
  <person name="Berin Loritsch" email="bloritsch@apache.org" id="BL"/>
  <person name="Stefano Mazzocchi" email="stefano@apache.org" id="SM"/>
  <person name="Michael Melhem" email="michaelm@apache.org" id="MM"/>
  <person name="Stephan Michels" email="stephan@apache.org" id="SMS"/>
  <person name="John Morrison" email="morrijr@apache.org" id="JM"/>
  <person name="Steven Noels" email="stevenn@apache.org" id="SN"/>
  <person name="Christopher Oliver" email="coliver@apache.org" id="CO"/>
  <person name="Giacomo Pati" email="giacomo@apache.org" id="GP"/>
  <person name="Konstantin Piroumian" email="kpiroumian@apache.org" id="KP"/>
  <person name="Marc Portier" email="mpo@apache.org" id="MPO"/>
  <person name="Ovidiu Predescu" email="ovidiu@apache.org" id="OP"/>
  <person name="Jeremy Quinn" email="jeremy@apache.org" id="JQ"/>
  <person name="Reinhard P&#246;tz" email="reinhard@apache.org" id="RP"/>
  <person name="Gianugo Rabellino" email="gianugo@apache.org" id="GR"/>
  <person name="Ricardo Rocha" email="ricardo@apache.org" id="RR"/>
  <person name="Peter Royal" email="proyal@apache.org" id="PAR"/>
  <person name="Paul Russell" email="prussell@apache.org" id="PR"/>
  <person name="Andrew Savory" email="asavory@apache.org" id="AS"/>
  <person name="Diana Shannon" email="shannon@apache.org" id="DS"/>
  <person name="Davanum Srinivas" email="dims@yahoo.com" id="DM"/>
  <person name="Jeff Turner" email="jefft@apache.org" id="JT"/>
  <person name="Upayavira" email="upayavira@apache.org" id="UV"/>
  <person name="Sylvain Wallez" email="sylvain@apache.org" id="SW"/>
  <person name="Carsten Ziegeler" email="cziegeler@apache.org" id="CZ"/>
  <person name="Volunteer needed" email="cocoon-dev@apache.org" id="open"/>
 </developers>
  
  <todo>
   <actions priority="high">
    <action context="code" assigned-to="all">
      Test, test, test :-)
    </action>   
 
    <action context="docs" assigned-to="open">
      Attend to any high+ issues in the
      <link href="plan/todo-doc.html">Documentation To Do List</link>
    </action>

    <action context="code" assigned-to="open">
      Attend to the general issues in the
      <link href="plan/release.html">release plan</link>
    </action>

    <action context="build" assigned-to="open">
      Complete (means put all allowed constructs and combinations)
      the lint/sitemap.xmap file. Enhance the RELAX NG grammar for sitemap.
    </action>

    <action context="code" assigned-to="SW">
      For 2.2: Views must start not from the first encountered label, but from the last one
      (see http://marc.theaimsgroup.com/?l=xml-cocoon-dev&amp;m=101784499622172&amp;w=2)
    </action>

    <action context="code" assigned-to="NKB">
      Make comprehensive samples with the handle-errors sitemap and real world
      use cases. Add also specific Selector and a FaqBuilder to be used by the
      NotifyingBuilder.
    </action>

    <action context="code" assigned-to="open">
      Finish the design and contracts of flow. Add more tests and samples and
      documentation.
    </action>

    <action context="code" assigned-to="open">
      Finish the
      <link href="plan/samples.html">refactoring of samples</link>
    </action>

    <action context="code" assigned-to="open">
      Finish moving the scratchpad stuff in main trunk.
    </action>

    <action context="code" assigned-to="SMS">
      Enable the 'use-store' parameter of the XSLT processor component. Test for occuring
      memory leaks. Seems only occuring if the xalan transformer is used. There also seems to be
      a problem during the serialization of the transient store, if the servlet container were
      stopped.
    </action>
   </actions>

   <actions priority="medium">
    <action context="code">
      EventRecorder classes in o.a.c.transformation.helpers package are similar
      to SaxBuffer. SaxBuffer should be extended (if it misses some functionality),
      and EventRecorder deprecated and removed.
    </action>

    <action context="code">
      XMLize exception handling so that error pages can become more
      semantically meaningful. Currently all XSP compilation errors are
      stored in a single string. With XMLized exceptions we could display
      especially XSP errors much nicer.
    </action>

    <action context="code">
      Remove all useless blank strings in XSP-generated code that hinder performances.
      This should be configurable (through an attribute?) to be able to keep them when
      needed.
    </action>

    <action context="code">
      Lucene is writing info to stdout when searching.
    </action>

    <action context="code">
      Redesign FragmentExtractorGenerator/Transformer so that it works on a clustered
      server: store fragments in the session rather than in a local store. <br/>
      This couldn't work, because if you working with caching pipelines, you cannot be sure
      that the entries are in the session(Stephan).
    </action>

    <action context="code">
      Examples are broken, if you went first to precept example
      (samples/precept/app/example1.html)
      and then to the xmlform example (samples/xmlform/wizard).
    </action>
   </actions>
  </todo>


  <changes>
 <release version="@version@" date="@date@">
    <action dev="AG" type="update">
     Updated jdtcore to 2.1.3, rhino1.5r4-continuations to 20040228
   </action>
   <action dev="JH" type="fix" fixes-bug="13904" due-to="Bernhard Huber" due-to-email="huber@apache.org">
     Ported fix from 2.1 to FilterTransformer.
   </action>
   <action dev="JH" type="fix" fixes-bug="27301">
     Fix namespace handling in FilterTransformer.
   </action>
   <action dev="JH" type="add" fixes-bug="27020" due-to="Peter Horsfield" due-to-email="peter@xml.grumpykitty.biz">
     Added grayscaling and color transformation to the ImageReader.
   </action>
   <action dev="JH" type="fix" fixes-bug="26851" due-to="Marco Rolappe" due-to-email="m_rolappe@web.de">
     LinkStatusGenerator now handles also links with a specified charset.
   </action>
   <action dev="JH" type="fix" fixes-bug="25594" due-to="Gernot Koller" due-to-email="grizzly@gmx.at">
     Allow streaming of uploaded files into a pipeline using StreamGenerator.
   </action>
   <action dev="JH" type="fix" fixes-bug="27254" due-to="Georg Ragaller" due-to-email="georg.ragaller@nse.de">
     Fixed path separator handling in cocoon.bat/.sh and Loader.java.
   </action>
   <action dev="AG" type="update">
     Updated xalan to 2.6.0
   </action>
   <action dev="CZ" type="update">
     Rewrote the request handling (external and internal).
   </action>
   <action dev="CZ" type="update">
     Update Avalon Excalibur packages to released versions.
   </action>
   <action dev="AG" type="update">
     Updated xerces to 2.6.2
   </action>
   <action dev="VG" type="remove">
     Remove non-FOM flow classes and system.js
   </action>
   <action dev="AG" type="update">
     Updated commons-httpclient to 2.0-final
   </action>
   <action dev="AG" type="update">
     Updated Ant to 1.6.1
   </action>
   <action dev="AG" type="update">
     Updated jdtcore to 2.1.2, Xerces to 2.6.1 and commons-jexl to 1.0-beta-1-20040113
   </action>
   <action dev="AG" type="update">
     Updated commons-collections to 3.0
   </action>
   <action dev="AG" type="update">
     Updated commons-httpclient to 2.0RC3
   </action>
   <action dev="AG" type="fix"  fixes-bug="25664" due-to-email="karel.vervaeke@pandora.be" due-to="Karel Vervaeke">
     build fails on windows without cygwin
   </action>
   <action dev="ALL" type="update">
     Upgrad of Avalon container (ECM => Fortress).
   </action>
   <action dev="ALL" type="remove">
     Removed all deprecated classes of 2.1.
   </action>
 </release>
  </changes>

</status>

