=== apache/cocoon/RELEASE_2_1_M_1/src/documentation/xdocs/dtd/book-cocoon-v10.dtd
<!-- ===================================================================
     
     Apache Cocoon Documentation Book DTD (Version 1.0)

PURPOSE:
This DTD defines the */book.xml documentation configuration files.

TYPICAL INVOCATION:

  <!DOCTYPE book PUBLIC
       "-//APACHE//DTD Cocoon Documentation Book Vx.yz//EN"
       "book-cocoon-vxyz.dtd">

  where 
  
    x := major version
    y := minor version
    z := status identifier (optional)
      
NOTES:
We need to replace this DTD with the proper one.
We are only using this DTD to enable validation during "build docs"
because every XML instance must declare its ruleset.

This initial minimal DTD has been reverse-engineered from the structure
of the current documents, e.g. 
 documentation/xdocs/book.xml
  
AUTHORS:
  David Crossley <crossley@apache.org>
  
FIXME:
  - find the proper DTD for book.xml

CHANGE HISTORY:
  20011031 Initial version. (DC)
    
COPYRIGHT:
  Copyright (c) @year@ The Apache Software Foundation.
  
  Permission to copy in any form is granted provided this notice is 
  included in all copies. Permission to redistribute is granted 
  provided this file is distributed untouched in all its parts and 
  included files.
  
==================================================================== -->

<!ELEMENT book (menu+)> 
<!ELEMENT menu (menu-item|external)*>
<!ELEMENT menu-item EMPTY>
<!ELEMENT external EMPTY>
<!ATTLIST book software CDATA #REQUIRED
               title CDATA #REQUIRED
               copyright CDATA #REQUIRED
               xmlns:xlink CDATA #IMPLIED
>
<!ATTLIST menu label CDATA #REQUIRED
>
<!ATTLIST menu-item label CDATA #REQUIRED
                    href CDATA #REQUIRED
                    type (visible|hidden) "visible"
>
<!ATTLIST external  label CDATA #REQUIRED
                    href CDATA #REQUIRED
                    type (visible|hidden) "visible"
>

<!-- =============================================================== -->
<!-- End of DTD -->
<!-- =============================================================== -->

=== apache/cocoon/RELEASE_2_1_8/src/documentation/xdocs/installing/book.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Copyright 1999-2004 The Apache Software Foundation

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->
<!DOCTYPE book PUBLIC "-//APACHE//DTD Cocoon Documentation Book V1.0//EN" "book-cocoon-v10.dtd">
<book software="Apache Cocoon" 
      title="Apache Cocoon Installation Documentation" 
      copyright="@year@ The Apache Software Foundation">

  <menu label="Navigation">
    <menu-item label="Main" href="../index.html"/>
  </menu>

  <menu label="Installation">
    <external  label="Download" href="http://cocoon.apache.org/mirror.cgi"/>

    <menu-item label="Intro" href="index.html"/>
    <menu-item label="Requirements" href="requirements.html"/>
    <menu-item label="Updating" href="updating.html"/>
    <menu-item label="Jars" href="jars.html"/>
  </menu>

  <menu label="Testing">
    <menu-item label="Overview" href="tests.html"/>
  </menu>

</book>

=== apache/cocoon/RELEASE_2_1_RC_1/src/documentation/xdocs/userdocs/xsp/book.xml
<?xml version="1.0"?>
<!DOCTYPE book PUBLIC "-//APACHE//DTD Cocoon Documentation Book V1.0//EN" "../../dtd/book-cocoon-v10.dtd">

<book software="Apache Cocoon" 
      title="Apache Cocoon XSP"
      copyright="@year@ The Apache Software Foundation">

  <menu label="Navigation">
    <menu-item label="Main" href="../../index.html"/>
    <menu-item label="User Documentation" href="../index.html"/>
  </menu>

  <menu label="XSP">
    <menu-item label="Overview" href="index.html"/>
    <menu-item label="XSP Guide" href="logicsheet.html"/>
    <menu-item label="XSP Internals" href="xsp-internals.html"/>
    <menu-item label="XSP Logicsheets" href="logicsheet-concepts.html"/>
    <menu-item label="Sessions" href="sessions.html"/>
  </menu>

  <menu label="Logicsheets">
    <menu-item label="Request" href="request.html"/>
    <menu-item label="Session" href="session.html"/>
    <menu-item label="ESQL" href="esql.html"/>
    <menu-item label="Forms" href="logicsheet-forms.html"/>
    <menu-item label="Sendmail" href="sendmail.html"/>
  </menu>

</book>
