=== apache/cocoon/branches/xml-cocoon2/CVSROOT/xdocs/dtd/document-v10.dtd
<!-- ===================================================================

     Apache Documentation DTD (Version 1.0)

PURPOSE:
  This DTD was developed to create a simple yet powerful document
  type for software documentation for use with the Apache projects.
  It is an XML-compliant DTD and it's maintained by the Apache XML
  project.

TYPICAL INVOCATION:

  <!DOCTYPE document PUBLIC
       "-//APACHE//DTD Documentation Vx.yz//EN"
       "http://xml.apache.org/DTD/document-vxyz.dtd">

  where

    x := major version
    y := minor version
    z := status identifier (optional)

NOTES:
  Many of the design patterns used in this DTD were take from the
  W3C XML Specification DTD edited by Eve Maler <elm@arbortext.com>.

  Where possible, great care has been used to reutilize HTML tag
  names to reduce learning efforts and to allow HTML editors to be
  used for complex authorings like tables and lists.

AUTHORS:
  Stefano Mazzocchi <stefano@apache.org>

FIXME:
  - how can we include char entities without hardwiring them?
  - should "form" tags be included?
  - should all style-free HTML 4.0 markup tags be included?
  - how do we handle the idea of "soft" xlinks?
  - should we add "soft" links to images?

CHANGE HISTORY:
  19991121 Initial version. (SM)
  19991123 Replaced "res" with more standard "strong" for emphasis. (SM)
  19991124 Added "fork" element for window forking behavior. (SM)
  19991124 Added "img-inline" element to separate from "img". (SM)
  19991129 Removed "affiliation" from "author". (SM)
  19991129 Made "author" empty and moved "name|email" as attributes. (SM)
  19991215 Simplified table section. (SM)
  19991215 Changed "img-block" in more friendly "figure". (SM)
  20000125 Added the "icon" image. (SM)
  20000126 Allowed "anchor" in all levels. (SM)
  20000404 Removed the "role" attribute from common-xxx.att. (SM)
  20000815 Allowed "code" inside "strong" and "em". (SM)

COPYRIGHT:
  Copyright (c) 1999-2000 The Apache Software Foundation.

  Permission to copy in any form is granted provided this notice is
  included in all copies. Permission to redistribute is granted
  provided this file is distributed untouched in all its parts and
  included files.

==================================================================== -->




<!-- =============================================================== -->
<!-- Common character entities (included from external file) -->
<!-- =============================================================== -->

<!-- FIXME (SM): this is hardcoding. Find a better way of doing this
     possibly using public identifiers of ISO latin char sets -->
<!ENTITY % charEntity SYSTEM "characters.ent">
%charEntity;




<!-- =============================================================== -->
<!-- Userful entitieis for increased DTD readability -->
<!-- =============================================================== -->

<!ENTITY % text "#PCDATA">


<!-- =============================================================== -->
<!-- Entities for general XML compliance -->
<!-- =============================================================== -->

<!-- Common attributes
        Every element has an ID attribute (sometimes required,
        but usually optional) for links. %common.att;
        is for common attributes where the ID is optional, and
        %common-idreq.att; is for common attributes where the
        ID is required.
-->
<!ENTITY % common.att
        'id                     ID              #IMPLIED
         xml:lang               NMTOKEN         #IMPLIED'>
<!ENTITY % common-idreq.att
        'id                     ID              #REQUIRED
         xml:lang               NMTOKEN         #IMPLIED'>


<!-- xml:space attribute ===============================================
        Indicates that the element contains white space
        that the formatter or other application should retain,
        as appropriate to its function.
==================================================================== -->
<!ENTITY % xmlspace.att
        'xml:space (default|preserve) #FIXED "preserve"'>


<!-- def attribute =====================================================
        Points to the element where the relevant definition can be
        found, using the IDREF mechanism.  %def.att; is for optional
        def attributes, and %def-req.att; is for required def
        attributes.
==================================================================== -->
<!ENTITY % def.att
        'def                    IDREF           #IMPLIED'>
<!ENTITY % def-req.att
        'def                    IDREF           #REQUIRED'>



<!-- ref attribute =====================================================
        Points to the element where more information can be found,
        using the IDREF mechanism.  %ref.att; is for optional
        ref attributes, and %ref-req.att; is for required ref
        attributes.
================================================================== -->
<!ENTITY % ref.att
        'ref                    IDREF           #IMPLIED'>
<!ENTITY % ref-req.att
        'ref                    IDREF           #REQUIRED'>


<!-- =============================================================== -->
<!-- Entities for XLink compliance -->
<!-- =============================================================== -->

<!ENTITY % xlink-simple.att
        'type      (simple|extended|locator|arc) #FIXED "simple"
         href      CDATA                         #IMPLIED
         role      CDATA                         #IMPLIED
         title     CDATA                         #IMPLIED '>
<!--    'xmlns     CDATA                         #FIXED "http://www.w3.org/XML/XLink/0.9" -->
<!-- FIXME: brain-dead IE5 has broken support for
     namespace validation and since I use it for editing
     I remove this for now -->

<!ENTITY % xlink-user-replace.att
        'show      (new|parsed|replace)   #FIXED "replace"
         actuate   (user|auto)            #FIXED "user" '>

<!ENTITY % xlink-user-new.att
        'show      (new|parsed|replace)   #FIXED "new"
         actuate   (user|auto)            #FIXED "user" '>

<!ENTITY % xlink-auto-parsed.att
        'show      (new|parsed|replace)   #FIXED "parsed"
         actuate   (user|auto)            #FIXED "auto" '>

<!-- FIXME (SM): XLink doesn't yet cover the idea of soft links so
     introducing it here using the same namespace is _somewhat_
     illegal. Should we create it own namespace?
-->
<!ENTITY % xlink-soft.att
        'mode      (hard|soft)            #FIXED "soft" '>


<!-- =============================================================== -->
<!-- Entities for general usage -->
<!-- =============================================================== -->


<!-- Key attribute =====================================================
        Optionally provides a sorting or indexing key, for cases when
        the element content is inappropriate for this purpose.
==================================================================== -->
<!ENTITY % key.att
        'key                    CDATA           #IMPLIED'>



<!-- Title attributes ==================================================
        Indicates that the element requires to have a title.
==================================================================== -->
<!ENTITY % title.att
        'title                  CDATA           #REQUIRED'>



<!-- Name attributes ==================================================
        Indicates that the element requires to have a name.
==================================================================== -->
<!ENTITY % name.att
        'name                   CDATA           #REQUIRED'>



<!-- Email attributes ==================================================
        Indicates that the element requires to have an email.
==================================================================== -->
<!ENTITY % email.att
        'email                  CDATA           #REQUIRED'>





<!-- =============================================================== -->
<!-- General definitions -->
<!-- =============================================================== -->

<!-- A person is a general human entity -->
<!ELEMENT person EMPTY>
<!ATTLIST person %common.att;
                 %name.att;
                 %email.att;>




<!-- =============================================================== -->
<!-- Content definitions -->
<!-- =============================================================== -->

<!ENTITY % local.content.mix "">

<!ENTITY % markup "strong|em|code|sub|sup">

<!ENTITY % links "link|connect|jump|fork|anchor">

<!ENTITY % special "br|img|icon">

<!ENTITY % link-content.mix "%text;|%markup;|%special;%local.content.mix;">

<!ENTITY % content.mix "%link-content.mix;|%links;">

    <!-- ==================================================== -->
    <!-- Phrase Markup -->
    <!-- ==================================================== -->

    <!-- Code (typically monospaced) -->
    <!ELEMENT code (%text;)>
    <!ATTLIST code %common.att;>

    <!-- Strong (typically bold) -->
    <!ELEMENT strong (%text;|code)*>
    <!ATTLIST strong %common.att;>

    <!-- Emphasis (typically italic) -->
    <!ELEMENT em (%text;|code)*>
    <!ATTLIST em %common.att;>

    <!-- Superscript (typically smaller and higher) -->
    <!ELEMENT sup (%text;)>
    <!ATTLIST sup %common.att;>

    <!-- Subscript (typically smaller and lower) -->
    <!ELEMENT sub (%text;)>
    <!ATTLIST sub %common.att;>

    <!-- FIXME (SM): should we add these HTML 4.0 markups
         which are style-free?

          -dfn
          -samp
          -kbd
          -var
          -cite
          -abbr
          -acronym

     -->

    <!-- ==================================================== -->
    <!-- Hypertextual Links -->
    <!-- ==================================================== -->

    <!-- hard replacing link (equivalent of <a ...>) -->
    <!ELEMENT link (%link-content.mix;)*>
    <!ATTLIST link %common.att;
                   %xlink-simple.att;
                   %xlink-user-replace.att;>

    <!-- Hard window replacing link (equivalent of <a ... target="_top">) -->
    <!ELEMENT jump (%link-content.mix;)*>
    <!ATTLIST jump %common.att;
                   %xlink-simple.att;
                   %xlink-user-new.att;>

    <!-- Hard window forking link (equivalent of <a ... target="_new">) -->
    <!ELEMENT fork (%link-content.mix;)*>
    <!ATTLIST fork %common.att;
                   %xlink-simple.att;
                   %xlink-user-new.att;>

    <!-- Anchor point (equivalent of <a name="...">) -->
    <!ELEMENT anchor EMPTY>
    <!ATTLIST anchor %common-idreq.att;>

    <!-- Soft link between processed pages (no equivalent in HTML) -->
    <!ELEMENT connect (%link-content.mix;)*>
    <!ATTLIST connect %common.att;
                      %xlink-simple.att;
                      %xlink-user-replace.att;
                      %xlink-soft.att;>

    <!-- ==================================================== -->
    <!-- Specials -->
    <!-- ==================================================== -->

    <!-- Breakline Object (typically forces line break) -->
    <!ELEMENT br EMPTY>
    <!ATTLIST br %common.att;>

    <!-- Image Object (typically an inlined image) -->
    <!-- FIXME (SM): should we have the notion of soft links even here
         for inlined objects? -->
    <!ELEMENT img EMPTY>
    <!ATTLIST img src    CDATA  #REQUIRED
                  alt    CDATA  #REQUIRED
                  height CDATA  #IMPLIED
                  width  CDATA  #IMPLIED
                  usemap CDATA  #IMPLIED
                  ismap  (ismap) #IMPLIED
                  %common.att;>

    <!-- Image Icon (typically an inlined image placed as graphical item) -->
    <!-- FIXME (SM): should we have the notion of soft links even here
         for inlined objects? -->
    <!ELEMENT icon EMPTY>
    <!ATTLIST icon src    CDATA  #REQUIRED
                   alt    CDATA  #REQUIRED
                   height CDATA  #IMPLIED
                   width  CDATA  #IMPLIED
                   %common.att;>




<!-- =============================================================== -->
<!-- Blocks definitions -->
<!-- =============================================================== -->

<!ENTITY % local.blocks "">

<!ENTITY % local.lists "">

<!ENTITY % paragraphs "p|source|note|fixme|figure">

<!ENTITY % tables "table">

<!ENTITY % lists "ol|ul|sl|dl %local.lists;">

<!ENTITY % blocks "anchor|%paragraphs;|%tables;|%lists; %local.blocks;">

    <!-- ==================================================== -->
    <!-- Paragraphs -->
    <!-- ==================================================== -->

    <!-- Text Paragraph (normally vertically space delimited) -->
    <!ELEMENT p (%content.mix;)*>
    <!ATTLIST p %common.att;>

    <!-- Source Paragraph (normally space is preserved) -->
    <!ELEMENT source (%content.mix;)*>
    <!ATTLIST source %common.att;
                     %xmlspace.att;>

    <!-- Note Paragraph (normally shown encapsulated) -->
    <!ELEMENT note (%content.mix;)*>
    <!ATTLIST note %common.att;>

    <!-- Fixme Paragraph (normally not shown) -->
    <!ELEMENT fixme (%content.mix;)*>
    <!-- the "author" attribute should match the "key" attribute of the
         <author> element -->
    <!ATTLIST fixme author CDATA #REQUIRED
                    %common.att;>

    <!-- ==================================================== -->
    <!-- Tables -->
    <!-- ==================================================== -->

    <!-- Attributes that indicate the spanning of the table cell -->
    <!ENTITY % cell.span 
        'colspan CDATA "1"
         rowspan CDATA "1"'>

    <!-- Table element -->
    <!ELEMENT table (caption?, tr+)>
    <!ATTLIST table %common.att;>

        <!-- The table title -->
        <!ELEMENT caption (%content.mix;)*>
        <!ATTLIST caption %common.att;>

        <!-- The table row element -->
        <!ELEMENT tr (th|td)+>
        <!ATTLIST tr %common.att;>

            <!-- The table row header element -->
            <!ELEMENT th (%content.mix;)*>
            <!ATTLIST th %common.att;
                         %cell.span;>

            <!-- The table row description element -->
            <!ELEMENT td (%content.mix;)*>
            <!ATTLIST td %common.att;
                         %cell.span;>

    <!-- ==================================================== -->
    <!-- Lists -->
    <!-- ==================================================== -->

    <!-- Unordered list (typically bulleted) -->
    <!ELEMENT ul (li|%lists;)+>
    <!--    spacing attribute:
            Use "normal" to get normal vertical spacing for items;
            use "compact" to get less spacing.  The default is dependent
            on the stylesheet. -->
    <!ATTLIST ul
            %common.att;
            spacing         (normal|compact)        #IMPLIED>

    <!-- Ordered list (typically numbered) -->
    <!ELEMENT ol (li|%lists;)+>
    <!--    spacing attribute:
            Use "normal" to get normal vertical spacing for items;
            use "compact" to get less spacing.  The default is dependent
            on the stylesheet. -->
    <!ATTLIST ol
            %common.att;
            spacing         (normal|compact)        #IMPLIED>

    <!-- Simple list (typically with no mark) -->
    <!ELEMENT sl (li|%lists;)+>
    <!ATTLIST sl %common.att;>

        <!-- List item -->
        <!ELEMENT li (%content.mix;|%lists;)*>
        <!ATTLIST li %common.att;>

    <!-- Definition list (typically two-column) -->
    <!ELEMENT dl (dt,dd)+>
    <!ATTLIST dl %common.att;>

        <!-- Definition term -->
        <!ELEMENT dt (%content.mix;)*>
        <!ATTLIST dt %common.att;>

        <!-- Definition description -->
        <!ELEMENT dd (%content.mix;)*>
        <!ATTLIST dd %common.att;>

    <!-- ==================================================== -->
    <!-- Special Blocks -->
    <!-- ==================================================== -->

    <!-- Image Block (typically a separated and centered image) -->
    <!-- FIXME (SM): should we have the notion of soft links even here
         for inlined objects? -->
    <!ELEMENT figure EMPTY>
    <!ATTLIST figure src    CDATA  #REQUIRED
                     alt    CDATA  #REQUIRED
                     height CDATA  #IMPLIED
                     width  CDATA  #IMPLIED
                     usemap CDATA  #IMPLIED
                     ismap  (ismap) #IMPLIED
                     %common.att;>





<!-- =============================================================== -->
<!-- Document -->
<!-- =============================================================== -->

<!ELEMENT document (header?, body, footer?)>
<!ATTLIST document %common.att;>

    <!-- ==================================================== -->
    <!-- Header -->
    <!-- ==================================================== -->

    <!ENTITY % local.headers "">

    <!ELEMENT header (title, subtitle?, version?, type?, authors,
                      notice*, abstract? %local.headers;)>
    <!ATTLIST header %common.att;>

    <!ELEMENT title (%text;)>
    <!ATTLIST title %common.att;>

    <!ELEMENT subtitle (%text;)>
    <!ATTLIST subtitle %common.att;>

    <!ELEMENT version (%text;)>
    <!ATTLIST version %common.att;>

    <!ELEMENT type (%text;)>
    <!ATTLIST type %common.att;>

    <!ELEMENT authors (person+)>
    <!ATTLIST authors %common.att;>

    <!ELEMENT notice (%content.mix;)*>
    <!ATTLIST notice %common.att;>

    <!ELEMENT abstract (%content.mix;)*>
    <!ATTLIST abstract %common.att;>

    <!-- ==================================================== -->
    <!-- Body -->
    <!-- ==================================================== -->

    <!ENTITY % local.sections "">

    <!ENTITY % sections "s1|anchor %local.sections;">

    <!ELEMENT body (%sections;)+>
    <!ATTLIST body %common.att;>

        <!ELEMENT s1 (s2|%blocks;)*>
        <!ATTLIST s1 %title.att; %common.att;>

            <!ELEMENT s2 (s3|%blocks;)*>
            <!ATTLIST s2 %title.att; %common.att;>

                <!ELEMENT s3 (s4|%blocks;)*>
                <!ATTLIST s3 %title.att; %common.att;>

                    <!ELEMENT s4 (%blocks;)*>
                    <!ATTLIST s4 %title.att; %common.att;>

    <!-- ==================================================== -->
    <!-- Footer -->
    <!-- ==================================================== -->

    <!ENTITY % local.footers "">

    <!ELEMENT footer (legal %local.footers;)>

        <!ELEMENT legal (%content.mix;)*>
        <!ATTLIST legal %common.att;>

<!-- =============================================================== -->
<!-- End of DTD -->
<!-- =============================================================== -->

=== apache/cocoon/src/documentation/xdocs/userdocs/actions/script-action.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!--
  Copyright 1999-2004 The Apache Software Foundation

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->
<!DOCTYPE document PUBLIC "-//APACHE//DTD Documentation V1.0//EN"
"../../dtd/document-v10.dtd">
<!--
  <![CDATA[ CVS Version: $Id: script-action.xml,v 1.3 2004/04/03 01:34:45 antonio Exp $ 
  ]]>  
--><document>
  <header>
    <title>ScriptAction in Cocoon</title>
    <version>0.9</version>
    <type>Technical document</type>
    <authors>
      <person email="huber@apache.org" name="Bernhard Huber" />
    </authors>
    <abstract>This document describes the ScriptAction of Cocoon.</abstract>
  </header>
  <body>
    <s1 title="ScriptAction">
      <table>
        <tr>
          <td>NAME</td>
          <td>script</td>
        </tr>
        <tr>
          <td>WHAT</td>
          <td>The <code>ScriptAction</code> component is used to executes any
          script that can be run by the BSF.</td>
        </tr>
        <tr>
          <td>TYPE</td>
          <td>Action</td>
        </tr>
        <tr>
          <td>BLOCK</td>
          <td>bsf</td>
        </tr>
        <tr>
          <td>CLASS</td>
          <td>org.apache.cocoon.action.ScriptAction</td>
        </tr>
        <tr>
          <td>SINCE</td>
          <td>Cocoon 2.1</td>
        </tr>
        <tr>
          <td>CACHEABLE</td>
          <td>not applicable</td>
        </tr>
      </table>
    </s1>
    <s1 title="Description">
      <p>A simple action that executes any script that can be run by the BSF
      system. BSF supports script languages like javascript, python, etc.</p>
    </s1>
    <s1 title="Usage">
      <p>This Action is used for quick prototyping of Action, realizing an
      Action in a script language instead of java language.</p>
      <s2 title="Sitemap pipeline examples">
        <p>The following sample executes the <code>script action/my-action.js</code>
        for each URI matching pattern <code>*.vm</code>. If the ScriptAction
        succeeds, the pipeline continues, invoking the VelocityGenerator, and
        serializing the XML stream.</p>
        <source>&#60;map:match pattern=&#34;*.vm&#34;&#62;
  &#60;map:action type=&#34;script&#34; src=&#34;action/my-action.js&#34;&#62;
    &#60;map:generate type=&#34;velocity&#34; src=&#34;{1}.vm&#34;/&#62;
    &#60;map:serialize/&#62;
  &#60;/map:action&#62;
&#60;/map:match&#62;
</source>
      </s2>
      <s2 title="Sitemap component configuration example">
        <p>The following sample configures an ScriptAction, naming it
        <code>script</code>.</p>
        <source>&#60;map:actions...
  &#60;map:action name=&#34;script&#34;
    src=&#34;org.apache.cocoon.acting.ScriptAction&#34;&#62; 
    logger=&#34;sitemap.action.script&#34;/&#62;    
    &#60;!-- optional action configuration --&#62;
    ...
&#60;/map:actions&#62;
</source>
      </s2>
      <s2 title="Configuration">
        <p>ScriptAction has no configuration options.</p>
      </s2>
      <s2 title="Setup">
        <p>ScriptAction determines the name of the script getting executed
        from its <code>src</code> attribute.</p>
        <p>The language of the script file is auto-detected by the BSF system
        from the extension of the script.
        </p>
        <p>The next table lists the default mapping of BSF:</p>
        <table>
          <tr>
            <th>Script language</th>
            <th>Extension</th>
          </tr>
          <tr>
            <td>javascript</td>
            <td>js</td>
          </tr>
          <tr>
            <td>jacl</td>
            <td>jacl</td>
          </tr>
          <tr>
            <td>netrexx</td>
            <td>nrx</td>
          </tr>
          <tr>
            <td>java</td>
            <td>java</td>
          </tr>
          <tr>
            <td>javaclass</td>
            <td>class</td>
          </tr>
          <tr>
            <td>bml</td>
            <td>bml</td>
          </tr>
          <tr>
            <td>vbscript</td>
            <td>vbs</td>
          </tr>
          <tr>
            <td>jscript</td>
            <td>jss</td>
          </tr>
          <tr>
            <td>perlscript</td>
            <td>pls</td>
          </tr>
          <tr>
            <td>perl</td>
            <td>pl</td>
          </tr>
          <tr>
            <td>jpython</td>
            <td>py</td>
          </tr>
          <tr>
            <td>lotusscript</td>
            <td>lss</td>
          </tr>
          <tr>
            <td>xslt</td>
            <td>xslt</td>
          </tr>
          <tr>
            <td>pnuts</td>
            <td>pnut</td>
          </tr>
          <tr>
            <td>beanbasic</td>
            <td>bb</td>
          </tr>
        </table>
        <p>ScriptAction registers following objects before invoking the
        script:</p>
        <table>
          <tr>
            <th>name</th>
            <th>Object Typ</th>
            <th>Comment</th>
          </tr>
          <tr>
            <td>resolver</td>
            <td>SourceResolver</td>
            <td>Cocoon&#39;s source resolver</td>
          </tr>
          <tr>
            <td>objectModel</td>
            <td>Map</td>
            <td>Cocoon&#39;s object model</td>
          </tr>
          <tr>
            <td>parameters</td>
            <td>Parameters</td>
            <td>Cocoon&#39;s action parameter</td>
          </tr>
          <tr>
            <td>actionMap</td>
            <td>Map</td>
            <td>Used for passing objects from the script back to the
            ScriptAction, and to Cocoon&#39;s sitemap</td>
          </tr>
          <tr>
            <td>logger</td>
            <td>Logger</td>
            <td>Cocoon&#39;s logger of this ScriptAction</td>
          </tr>
          <tr>
            <td>request</td>
            <td>Request</td>
            <td>Request provided by the object model</td>
          </tr>
          <tr>
            <td>scriptaction</td>
            <td>Action</td>
            <td>The instance of this ScriptAction</td>
          </tr>
          <tr>
            <td>manager</td>
            <td>Manager</td>
            <td>Cocoon&#39;s manager of this ScriptAction</td>
          </tr>
        </table>
        <p>These objects are accessible from within the script.</p>
      </s2>
      <s2 title="Effect on Object Model and Sitemap Parameters">
        <p>ScriptAction checks the existence of the key <code>scriptaction-continue</code>
        in the <code>actionMap</code>. If this key exists ScriptAction returns
        <code>actionMap</code>, otherwise <code>null</code> is returned.</p>
        <p>Objects available in the <code>actionMap</code> are available in
        the sitemap.</p>
      </s2>
    </s1>
    <s1 title="Bugs/Caveats">
      <p>Using ScriptAction relies heavily on the setting of the key
      <code>scriptaction-continue</code> in the <code>mapAction</code>.</p>
      <p>Be aware to provide script language implementation, beside BSF implementation.
      </p>
    </s1>
    <s1 title="History">
      <p>07-24-03: initial creation</p>
      <p>04-02-04: Updated to Jakarta BSF</p>
    </s1>
    <s1 title="Copyright">
      <p>Copyright (C) 1999-2004 The Apache Software Foundation. All rights
      reserved.</p>
    </s1>
    <s1 title="See also">
      <p><!-- Links to related components pages. -->A general documentation
      about actions is available at <link href="../concepts/actions.html">Actions</link>.</p>
      <p>Further Documentation visit <link
      href="http://jakarta.apache.org/bsf/index.html">Jakarta BSF Project</link>.</p>
    </s1>
  </body>
</document>

=== apache/cocoon/branches/xml-cocoon2/CVSROOT/xdocs/image-encoders.xml
<?xml version="1.0"?>

<!--
<!DOCTYPE document SYSTEM "./dtd/document-v10.dtd">
-->
<?xml-stylesheet href="document2html.xsl" type="text/xsl"?>

<document>
 <header>
  <title>Image Encoders</title>
  <authors>
   <person name="Ross Burton" email="rossb@apache.org"/>
  </authors>
 </header>

 <body>
   <s1 title="Introduction">
	  <p>Conceptually, an image encoder takes an image and an output stream, and converts the image into a graphics file which is sent through the stream.</p>
		<p>A typical example of use is the Cocoon 2 SVG Serializer, which renders a SVG onto a <code>BufferedImage</code> object. Then an image encoder is called with this image and the <code>OutputStream</code> to the client, who then receives the image.</p>
	 </s1>
   <s1 title="Implementing an ImageEncoder">
	  <p>The ImageEncoder interface is very simple as there are only two methods to implement: <code>getMimeType()</code> and <code>encode()</code>. The interface is also <ref>Avalon</ref>-aware as it extends the Avalon core interface <code>Component</code>.</p>
	  <s2 title="String getMimeType()">
		 <p>This function returns the MIME type of the image file type generated, for example "image/png". A null object is a valid return value. If an encoder returns null, the application must be able to use a MIME type specified elsewhere. For instance, Cocoon 2 has a <code>mime-type</code> attribute in the serializer declaration which is used as a backup value.</p>
		</s2>
	  <s2 title="void encode(BufferedImage img, OutputStream out) throws IOException">
		 <p>This method perfoms the encoding of the image.</p>
		</s2>
	 </s1>
   <s1 title="Configuration">
	  <p>Potential users of this component may be wondering how to configure the encoder. While it is true that there is no configuration support in the interface, it is possible through the <ref>Avalon</ref> <code>Configurable</code> interface. Implement this interface and (in an <ref>Avalon</ref>-aware server) the component manager will call <code>setConfiguration(Configuration conf)</code> immediately after creating the encoder.</p>
		<ul>
		 <li>Migrate to <ref>Avalon</ref>. Minimal support of the <ref>Avalon</ref> concepts is fairly trivial.</li>
		 <li>Replicate the behaviour of the Component Manager and create a <code>Configuration</code> object to pass to the image encoder.</li>
		</ul>
	 </s1>
 </body>
</document>
